### ISSUE TITLE
Timetable destinations are not comprehensive

### ISSUE THREAD

**Issue by howff** [metroapps/national_rail_timetable#3]
For example BYF departures are listed only via Arbroath towards Inverness, and via Dundee towards Glasgow, but no mention of trains heading towards Edinburgh and beyond.
https://gbtt.uk/timetable/BYF

**Comment by miklcct** [comment]
There are no direct passenger trains from Broughty Ferry to Edinburgh and beyond.

If you change the date to 2024-09-08, you should see a train to Edinburgh.
